Added preserveAPMode setting
Hieromon/AutoConnect pull request #217
Opened 2020-05-04 18:21 UTC by TKTF50

Hi Hieromon,

Here is the code change that allows me to successfully use ESP-Now in my sketch. I added a new configuration setting `preserveAPMode` that avoids any changes to the soft AP mode settings when AutoConnect.begin is called.

I limited the change so that it **only** applies in the case where the code is using AutoConnect.begin to attempt to connect to the WLAN but **will not** start the portal in the event of a failure (autoRise is false). This should avoid damaging any existing behaviour.

Thanks for considering this change.
resolves  Hieromon/AutoConnect#210

2020-05-11 04:57 UTC, Hieromon requested changes
@TKTF50 Thank you for PR.
I reviewed your PR, and the results are:
1. No changed basically for the logic of PR.
2. Changed the name of `preserveAPMode` to the `preserveWiFiMode`.
  It's not so important but more directly represents the behavior of PR. Actually, it doesn't start the AP. (Needs to WiFi.softAP before calling AutoConnect::begin)
3. Removed AC_DEBUG's PSTR. (it converges to the macro itself with v120)
    https://github.com/Hieromon/AutoConnect/blob/bef08e1be34f79f03388e0fd1ed2200af6c41963/src/AutoConnectDefs.h#L21-L22

I pushed the results to branch [pr/217](https://github.com/Hieromon/AutoConnect/tree/pr/217). Please evaluate it and submit the issue if you will have.
After we agree for the changes, I will merge into v120.

Thank you for your contribution.

2020-05-11 17:02 UTC, TKTF50 commented
@Hieromon,
Thanks for reviewing the PR.

I've given it some thought and I think that my original name for the variable (`preserveAPMode`) is a better choice. Here's why:

You are right that this option does not start the AP mode, but the word "preserve" means to "maintain (something) in its original or existing state".

When the `begin` method is called with this new setting, only the AP mode bit will be kept unchanged. If AP was not set before `begin `was called, it will not be set when `begin `returns. If it was set, it will still be set when `begin `returns. But the STA mode bit will be set regardless of whether it was set or not before calling `begin`. So, with this new option, we are not preserving the entire WiFi mode, only the AP mode.

Let me know what you think.
Thanks!

2020-05-12 09:35 UTC, Hieromon reviewed
@TKTF50 Thank you reply.
> name for the variable (preserveAPMode) is a better choice. 
> we are not preserving the entire WiFi mode, only the AP mode.

I understood your intention, and it's reasonable. Below is a quote from the espressif8266 non-os SDK API Reference and it states the value of opmode as:
```cpp
bool wifi_set_opmode(uint8 opmode)
0x01: Station mode      .... ...x
0x02: SoftAP mode       .... ..x.
0x03: Station + SoftAP  .... ..xx
```
So, `preserveAPMode` means that it maintains the SoftAP mode **bit**. It's exactly.
The [pr/217](https://github.com/Hieromon/AutoConnect/tree/pr/217) has reverted to your original name of `preserveAPMode`.
Anything else?

2020-05-12 19:47 UTC, TKTF50 commented
@Hieromon,

I have no other concerns regarding the code change.

Thank you for including this in your library.

2020-05-13 07:54 UTC, Hieromon approved these changes

2020-05-13 08:04 UTC, merged